from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  database ="db_pbo"
)
mycursor = mydb.cursor()


class Ui_wdw_daftarpegakun(object):
    def setupUi(self, wdw_daftarpegakun):
        wdw_daftarpegakun.setObjectName("wdw_daftarpegakun")
        wdw_daftarpegakun.resize(745, 510)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdw_daftarpegakun.sizePolicy().hasHeightForWidth())
        wdw_daftarpegakun.setSizePolicy(sizePolicy)
        wdw_daftarpegakun.setMinimumSize(QtCore.QSize(745, 510))
        wdw_daftarpegakun.setMaximumSize(QtCore.QSize(745, 510))
        self.centralwidget = QtWidgets.QWidget(wdw_daftarpegakun)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(10, 10, 61, 41))
        self.btn_back.setObjectName("btn_back")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(240, 10, 501, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.TabelPegawai = QtWidgets.QWidget()
        self.TabelPegawai.setObjectName("TabelPegawai")
        self.tableWidget = QtWidgets.QTableWidget(self.TabelPegawai)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 471, 401))
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.inp_rowdel = QtWidgets.QComboBox(self.TabelPegawai)
        self.inp_rowdel.setGeometry(QtCore.QRect(350, 410, 69, 21))
        self.inp_rowdel.setObjectName("inp_rowdel")
        self.btn_del = QtWidgets.QPushButton(self.TabelPegawai)
        self.btn_del.setGeometry(QtCore.QRect(430, 410, 51, 21))
        self.btn_del.setObjectName("btn_del")
        self.tabWidget.addTab(self.TabelPegawai, "")
        self.TabelAkun = QtWidgets.QWidget()
        self.TabelAkun.setObjectName("TabelAkun")
        self.btn_del_2 = QtWidgets.QPushButton(self.TabelAkun)
        self.btn_del_2.setGeometry(QtCore.QRect(430, 410, 51, 21))
        self.btn_del_2.setObjectName("btn_del_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.TabelAkun)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 0, 471, 401))
        self.tableWidget_2.setRowCount(20)
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.inp_rowdel_2 = QtWidgets.QComboBox(self.TabelAkun)
        self.inp_rowdel_2.setGeometry(QtCore.QRect(350, 410, 69, 21))
        self.inp_rowdel_2.setObjectName("inp_rowdel_2")
        self.tabWidget.addTab(self.TabelAkun, "")
        self.tabWidget0 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget0.setGeometry(QtCore.QRect(10, 60, 221, 421))
        self.tabWidget0.setObjectName("tabWidget0")
        self.tab_inp0 = QtWidgets.QWidget()
        self.tab_inp0.setObjectName("tab_inp0")
        self.lbl_alamat = QtWidgets.QLabel(self.tab_inp0)
        self.lbl_alamat.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.lbl_alamat.setObjectName("lbl_alamat")
        self.inp_nampgw = QtWidgets.QLineEdit(self.tab_inp0)
        self.inp_nampgw.setGeometry(QtCore.QRect(10, 100, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inp_nampgw.sizePolicy().hasHeightForWidth())
        self.inp_nampgw.setSizePolicy(sizePolicy)
        self.inp_nampgw.setText("")
        self.inp_nampgw.setObjectName("inp_nampgw")
        self.inp_nip = QtWidgets.QLineEdit(self.tab_inp0)
        self.inp_nip.setGeometry(QtCore.QRect(10, 40, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inp_nip.sizePolicy().hasHeightForWidth())
        self.inp_nip.setSizePolicy(sizePolicy)
        self.inp_nip.setText("")
        self.inp_nip.setObjectName("inp_nip")
        self.inp_jabpgw = QtWidgets.QLineEdit(self.tab_inp0)
        self.inp_jabpgw.setGeometry(QtCore.QRect(10, 280, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inp_jabpgw.sizePolicy().hasHeightForWidth())
        self.inp_jabpgw.setSizePolicy(sizePolicy)
        self.inp_jabpgw.setText("")
        self.inp_jabpgw.setObjectName("inp_jabpgw")
        self.lbl_jabpgw = QtWidgets.QLabel(self.tab_inp0)
        self.lbl_jabpgw.setGeometry(QtCore.QRect(10, 260, 91, 16))
        self.lbl_jabpgw.setObjectName("lbl_jabpgw")
        self.inp_notelp = QtWidgets.QLineEdit(self.tab_inp0)
        self.inp_notelp.setGeometry(QtCore.QRect(10, 220, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inp_notelp.sizePolicy().hasHeightForWidth())
        self.inp_notelp.setSizePolicy(sizePolicy)
        self.inp_notelp.setText("")
        self.inp_notelp.setObjectName("inp_notelp")
        self.lbl_notelp = QtWidgets.QLabel(self.tab_inp0)
        self.lbl_notelp.setGeometry(QtCore.QRect(10, 200, 101, 16))
        self.lbl_notelp.setObjectName("lbl_notelp")
        self.lbl_nampgw = QtWidgets.QLabel(self.tab_inp0)
        self.lbl_nampgw.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.lbl_nampgw.setObjectName("lbl_nampgw")
        self.lbl_nip = QtWidgets.QLabel(self.tab_inp0)
        self.lbl_nip.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.lbl_nip.setObjectName("lbl_nip")
        self.lbl_title = QtWidgets.QLabel(self.tab_inp0)
        self.lbl_title.setGeometry(QtCore.QRect(10, 0, 91, 21))
        self.lbl_title.setObjectName("lbl_title")
        self.btn_submit = QtWidgets.QPushButton(self.tab_inp0)
        self.btn_submit.setGeometry(QtCore.QRect(0, 370, 211, 23))
        self.btn_submit.setObjectName("btn_submit")
        self.inp_alamat = QtWidgets.QLineEdit(self.tab_inp0)
        self.inp_alamat.setGeometry(QtCore.QRect(10, 160, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inp_alamat.sizePolicy().hasHeightForWidth())
        self.inp_alamat.setSizePolicy(sizePolicy)
        self.inp_alamat.setText("")
        self.inp_alamat.setObjectName("inp_alamat")
        self.tabWidget0.addTab(self.tab_inp0, "")
        self.tab_inp1 = QtWidgets.QWidget()
        self.tab_inp1.setObjectName("tab_inp1")
        self.lbl_nip_2 = QtWidgets.QLabel(self.tab_inp1)
        self.lbl_nip_2.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.lbl_nip_2.setObjectName("lbl_nip_2")
        self.lbl_title_2 = QtWidgets.QLabel(self.tab_inp1)
        self.lbl_title_2.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.lbl_title_2.setObjectName("lbl_title_2")
        self.lbl_uname = QtWidgets.QLabel(self.tab_inp1)
        self.lbl_uname.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.lbl_uname.setObjectName("lbl_uname")
        self.lbl_pass = QtWidgets.QLabel(self.tab_inp1)
        self.lbl_pass.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.lbl_pass.setObjectName("lbl_pass")
        self.inp_uname = QtWidgets.QLineEdit(self.tab_inp1)
        self.inp_uname.setGeometry(QtCore.QRect(10, 40, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inp_uname.sizePolicy().hasHeightForWidth())
        self.inp_uname.setSizePolicy(sizePolicy)
        self.inp_uname.setText("")
        self.inp_uname.setObjectName("inp_uname")
        self.lbl_notelp_2 = QtWidgets.QLabel(self.tab_inp1)
        self.lbl_notelp_2.setGeometry(QtCore.QRect(10, 200, 101, 16))
        self.lbl_notelp_2.setObjectName("lbl_notelp_2")
        self.inp_pass = QtWidgets.QLineEdit(self.tab_inp1)
        self.inp_pass.setGeometry(QtCore.QRect(10, 160, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inp_pass.sizePolicy().hasHeightForWidth())
        self.inp_pass.setSizePolicy(sizePolicy)
        self.inp_pass.setInputMask("")
        self.inp_pass.setText("")
        self.inp_pass.setObjectName("inp_pass")
        self.btn_submit_2 = QtWidgets.QPushButton(self.tab_inp1)
        self.btn_submit_2.setGeometry(QtCore.QRect(0, 370, 211, 23))
        self.btn_submit_2.setObjectName("btn_submit_2")
        self.inp_combnip = QtWidgets.QComboBox(self.tab_inp1)
        self.inp_combnip.setGeometry(QtCore.QRect(10, 100, 111, 22))
        self.inp_combnip.setObjectName("inp_combnip")
        self.inp_combrole = QtWidgets.QComboBox(self.tab_inp1)
        self.inp_combrole.setGeometry(QtCore.QRect(10, 220, 111, 22))
        self.inp_combrole.setObjectName("inp_combrole")
        self.inp_combrole.addItem("")
        self.inp_combrole.addItem("")
        self.tabWidget0.addTab(self.tab_inp1, "")
        wdw_daftarpegakun.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(wdw_daftarpegakun)
        self.statusbar.setObjectName("statusbar")
        wdw_daftarpegakun.setStatusBar(self.statusbar)
        self.connectingakn()
        self.connectingpgw()
        self.refresh()
        #################################START#################################
        self.btn_submit.pressed.connect(self.submitpgw)
        self.btn_submit_2.pressed.connect(self.submitakn)
        #################################ENDS##################################

        self.retranslateUi(wdw_daftarpegakun)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget0.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdw_daftarpegakun)

    def retranslateUi(self, wdw_daftarpegakun):
        _translate = QtCore.QCoreApplication.translate
        wdw_daftarpegakun.setWindowTitle(_translate("wdw_daftarpegakun", "Daftar Pegawai & Akun"))
        self.btn_back.setText(_translate("wdw_daftarpegakun", "Kembali"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("wdw_daftarpegakun", "NIP"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("wdw_daftarpegakun", "Nama Pegawai"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("wdw_daftarpegakun", "Alamat"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("wdw_daftarpegakun", "Nomor Telepon/HP"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("wdw_daftarpegakun", "Jabatan Pegawai"))
        self.btn_del.setText(_translate("wdw_daftarpegakun", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabelPegawai), _translate("wdw_daftarpegakun", "Tabel Pegawai"))
        self.btn_del_2.setText(_translate("wdw_daftarpegakun", "Delete"))
        self.tableWidget_2.setSortingEnabled(True)
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("wdw_daftarpegakun", "Usernam"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("wdw_daftarpegakun", "NIP"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("wdw_daftarpegakun", "Password"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("wdw_daftarpegakun", "Role Akun"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabelAkun), _translate("wdw_daftarpegakun", "Tabel Akun"))
        self.lbl_alamat.setText(_translate("wdw_daftarpegakun", "Alamat"))
        self.inp_nampgw.setPlaceholderText(_translate("wdw_daftarpegakun", "ex. Joko Widodo"))
        self.inp_nip.setPlaceholderText(_translate("wdw_daftarpegakun", "ex. 1191401941"))
        self.inp_jabpgw.setPlaceholderText(_translate("wdw_daftarpegakun", "ex. OB"))
        self.lbl_jabpgw.setText(_translate("wdw_daftarpegakun", "Jabatan Pegawai"))
        self.inp_notelp.setPlaceholderText(_translate("wdw_daftarpegakun", "ex. +628628862"))
        self.lbl_notelp.setText(_translate("wdw_daftarpegakun", "Nomor Telepon/HP"))
        self.lbl_nampgw.setText(_translate("wdw_daftarpegakun", "Nama Pegawai"))
        self.lbl_nip.setText(_translate("wdw_daftarpegakun", "NIP"))
        self.lbl_title.setText(_translate("wdw_daftarpegakun", "Tambah Pegawai"))
        self.btn_submit.setText(_translate("wdw_daftarpegakun", "Submit"))
        self.inp_alamat.setPlaceholderText(_translate("wdw_daftarpegakun", "ex. Jl. Jalanan No. 22"))
        self.tabWidget0.setTabText(self.tabWidget0.indexOf(self.tab_inp0), _translate("wdw_daftarpegakun", "Input Pegawai"))
        self.lbl_nip_2.setText(_translate("wdw_daftarpegakun", "NIP"))
        self.lbl_title_2.setText(_translate("wdw_daftarpegakun", "Tambah User"))
        self.lbl_uname.setText(_translate("wdw_daftarpegakun", "Username"))
        self.lbl_pass.setText(_translate("wdw_daftarpegakun", "Password"))
        self.inp_uname.setPlaceholderText(_translate("wdw_daftarpegakun", "ex. xXPussySlayer69Xx"))
        self.lbl_notelp_2.setText(_translate("wdw_daftarpegakun", "Role Akun"))
        self.inp_pass.setPlaceholderText(_translate("wdw_daftarpegakun", "ex. ********"))
        self.btn_submit_2.setText(_translate("wdw_daftarpegakun", "Submit"))
        self.inp_combrole.setItemText(0, _translate("wdw_daftarpegakun", "admin"))
        self.inp_combrole.setItemText(1, _translate("wdw_daftarpegakun", "user"))
        self.tabWidget0.setTabText(self.tabWidget0.indexOf(self.tab_inp1), _translate("wdw_daftarpegakun", "Input User"))

    def connectingpgw(self):
        order = "SELECT * FROM pegawai"
        mycursor.execute(order)
        data = mycursor.fetchall()
        if not data:
            self.tableWidget.setColumnCount(1)
            self.tableWidget.setRowCount(1)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(0, 0, item)
            item = self.tableWidget.item(0, 0)
            item.setText("NULL")
        else:
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(data):
                self.tableWidget.insertRow(row_number)
                for column_number, ndata in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(ndata)))

    def connectingakn(self):
        order = "SELECT * FROM login_info"
        mycursor.execute(order)
        data = mycursor.fetchall()
        if not data:
            self.tableWidget_2.setColumnCount(1)
            self.tableWidget_2.setRowCount(1)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setVerticalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setHorizontalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(0, 0, item)
            item = self.tableWidget_2.item(0, 0)
            item.setText("NULL")
        else:
            self.tableWidget_2.setRowCount(0)
            for row_number, row_data in enumerate(data):
                self.tableWidget_2.insertRow(row_number)
                for column_number, ndata in enumerate(row_data):
                    self.tableWidget_2.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(ndata)))

    def combo(self):
        order = "SELECT nip FROM pegawai"
        mycursor.execute(order)
        data = mycursor.fetchall()
        mydb.commit()
        return data

    def refresh(self):
        self.inp_combnip.clear()
        self.data = []
        self.data1 = self.combo()
        for i in self.data1:
            self.data.append(i[0])
        self.inp_combnip.addItems(self.data)

    
    def submitpgw(self):
        nip = self.inp_nip.text()
        nampgw = self.inp_nampgw.text()
        alamat = self.inp_alamat.text()
        notelp = self.inp_notelp.text()
        jabpeg = self.inp_jabpgw.text()
        try:
            sql_insert_blob_query = """ INSERT INTO pegawai
                            (nip, nama_pegawai, alamat, no_telp, role) VALUES (%s,%s,%s,%s,%s)"""
            inputdat = (nip, nampgw, alamat, notelp, jabpeg)
            result = mycursor.execute(sql_insert_blob_query,inputdat)
            mydb.commit()
        except mysql.connector.Error as error:
            self.show_Popup(f'Gagal Mengunggah Data Peminjaman\nError Code\n{error}')
            masuk = 0
        self.connectingpgw()
        self.refresh()

    def submitakn(self):
        uname = self.inp_uname.text()
        combnip = self.inp_combnip.currentText()
        passw = self.inp_pass.text()
        role = self.inp_combrole.currentText()

        try:
            sql_insert_blob_query = """ INSERT INTO login_info
                            (username, nip, password, account_role) VALUES (%s,%s,%s,%s)"""
            inputdat = (uname,combnip,passw,role)
            result = mycursor.execute(sql_insert_blob_query,inputdat)
            mydb.commit()
        except mysql.connector.Error as error:
            self.show_Popup(f'Gagal Mengunggah Data Peminjaman\nError Code\n{error}')
            masuk = 0
        self.connectingakn()

    def show_Popup(self,message):
        msg = QMessageBox()
        msg.setWindowTitle("Login info")
        msg.setText(message)
        x = msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdw_daftarpegakun = QtWidgets.QMainWindow()
    ui = Ui_wdw_daftarpegakun()
    ui.setupUi(wdw_daftarpegakun)
    wdw_daftarpegakun.show()
    sys.exit(app.exec_())
